# Generated by Django 4.1.7 on 2023-06-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("discount", models.CharField(max_length=20, verbose_name="Discount")),
                ("price", models.CharField(max_length=20, verbose_name="Price")),
            ],
            options={
                "db_table": "new_table",
            },
        ),
    ]
