# Generated by Django 4.1.7 on 2023-07-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="discounts",
            table=None,
        ),
    ]
