# Generated by Django 4.1.7 on 2023-08-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
    ]
