# Generated by Django 4.1.7 on 2023-08-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_todo_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="text",
            field=models.TextField(max_length=500, verbose_name="TODOs"),
        ),
    ]
